version = 0
name = "EndSessions"
documentation = "EndSessions performs an endSessions operation."

[properties]
disabled = ["collection", "database"]

[command]
name = "endSessions"
parameter = "sessionIDs"

[request.sessionIDs]
type = "array"
documentation = "sessionIDs specify the sessions to be expired."
skip = true
constructor = true
