name: Publish
description: Publish Draft GitHub Release
inputs:
  version:
    description: The published version
    required: true
  prev_version:
    description: The previous version
    required: true
  push_changes:
    description: Whether to push the changes
    default: "true"
runs:
  using: composite
  steps:
    - name: Generate the notes
      shell: bash -eux {0}
      run: |
        cd ${{ github.action_path }}
        go run notes.go ${{ inputs.version }} ${{ inputs.prev_version }}
        cat forum.md >> $GITHUB_STEP_SUMMARY
        rm forum.md
    - name: Create GitHub Release
      shell: bash -eux {0}
      run: |
        echo "Creating draft release"
        cd ${{ github.action_path }}
        export VERSION=${{inputs.version}}
        if [ "${{ inputs.push_changes }}" == "true" ]; then
          gh release create ${VERSION} --draft --verify-tag --title ${VERSION} -F github.md
          gh release view ${VERSION} >> $GITHUB_STEP_SUMMARY
        else
          echo "## Skipping draft release with notes:" >> $GITHUB_STEP_SUMMARY
          cat github.md >> $GITHUB_STEP_SUMMARY
        fi
        rm github.md