AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Go Driver lambda function test

Parameters:
  MongoDbUri:
    Type: String
    Description: The MongoDB connection string.

Globals:
  Function:
    Timeout: 30

Resources:
  MongoDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mongodb/
      Handler: mongodb
      Runtime: go1.x
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
      Architectures:
      - x86_64
      Events:
        MongoDB:
          Type: Api
          Properties:
            Path: /mongodb
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MongoDBApi:
    Description: "API Gateway endpoint URL for Prod stage for MongoDB function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  MongoDBFunction:
    Description: "MongoDB Lambda Function ARN"
    Value: !GetAtt MongoDBFunction.Arn
  MongoDBFunctionIamRole:
    Description: "Implicit IAM Role created for MongoDB function"
    Value: !GetAtt MongoDBFunctionRole.Arn

