name: PR API Report
on:
  pull_request_target:

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        issues: write
    steps:
    - uses: actions/setup-go@v4
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: "## API Change Report"

    - name: Create the comment body
      run: |
        set -eux
        git clone https://github.com/mongodb/mongo-go-driver
        cd mongo-go-driver
        git remote add source https://github.com/$GITHUB_ACTOR/mongo-go-driver
        git fetch origin $GITHUB_BASE_REF
        git fetch source $GITHUB_HEAD_REF
        git checkout $GITHUB_HEAD_REF
        make api-report
        cat api-report.md

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: 'mongo-go-driver/api-report.md'
        edit-mode: replace